imports:
  root: ../__package__.yml
service:
  auth: false
  base-path: ''
  endpoints:
    list:
      path: /api/storages/localfiles/
      method: GET
      auth: true
      docs: Get a list of all local file import storage connections.
      display-name: Get all import storage
      request:
        name: LocalListRequest
        query-parameters:
          project:
            type: optional<integer>
            docs: Project ID
      response:
        docs: ''
        type: list<root.LocalFilesImportStorage>
      examples:
        - response:
            body:
              - id: 1
                type: type
                synchronizable: true
                path: path
                regex_filter: regex_filter
                use_blob_urls: true
                last_sync: '2024-01-15T09:30:00Z'
                last_sync_count: 1
                last_sync_job: last_sync_job
                status: initialized
                traceback: traceback
                meta:
                  meta:
                    key: value
                title: title
                description: description
                created_at: '2024-01-15T09:30:00Z'
                project: 1
      audiences:
        - public
    create:
      path: /api/storages/localfiles/
      method: POST
      auth: true
      docs: Create a new local file import storage connection.
      display-name: Create import storage
      request:
        name: LocalCreateRequest
        body:
          properties:
            project:
              type: optional<integer>
              docs: Project ID
            path:
              type: optional<string>
              docs: Local path
            regex_filter:
              type: optional<string>
              docs: Regex for filtering objects
            use_blob_urls:
              type: optional<boolean>
              docs: Interpret objects as BLOBs and generate URLs
      response:
        docs: ''
        type: LocalCreateResponse
      examples:
        - request: {}
          response:
            body:
              project: 1
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
      audiences:
        - public
    validate:
      path: /api/storages/localfiles/validate
      method: POST
      auth: true
      docs: Validate a specific local file import storage connection.
      display-name: Validate import storage
      response:
        docs: ''
        type: root.LocalFilesImportStorage
      examples:
        - response:
            body:
              id: 1
              type: type
              synchronizable: true
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              status: initialized
              traceback: traceback
              meta:
                meta:
                  key: value
              title: title
              description: description
              created_at: '2024-01-15T09:30:00Z'
              project: 1
      audiences:
        - public
    get:
      path: /api/storages/localfiles/{id}
      method: GET
      auth: true
      docs: Get a specific local file import storage connection.
      path-parameters:
        id:
          type: integer
          docs: A unique integer value identifying this local files import storage.
      display-name: Get import storage
      response:
        docs: ''
        type: root.LocalFilesImportStorage
      examples:
        - path-parameters:
            id: 1
          response:
            body:
              id: 1
              type: type
              synchronizable: true
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              status: initialized
              traceback: traceback
              meta:
                meta:
                  key: value
              title: title
              description: description
              created_at: '2024-01-15T09:30:00Z'
              project: 1
      audiences:
        - public
    delete:
      path: /api/storages/localfiles/{id}
      method: DELETE
      auth: true
      docs: Delete a specific local import storage connection.
      path-parameters:
        id:
          type: integer
          docs: A unique integer value identifying this local files import storage.
      display-name: Delete import storage
      examples:
        - path-parameters:
            id: 1
      audiences:
        - public
    update:
      path: /api/storages/localfiles/{id}
      method: PATCH
      auth: true
      docs: Update a specific local file import storage connection.
      path-parameters:
        id:
          type: integer
          docs: A unique integer value identifying this local files import storage.
      display-name: Update import storage
      request:
        name: LocalUpdateRequest
        body:
          properties:
            project:
              type: optional<integer>
              docs: Project ID
            path:
              type: optional<string>
              docs: Local path
            regex_filter:
              type: optional<string>
              docs: Regex for filtering objects
            use_blob_urls:
              type: optional<boolean>
              docs: Interpret objects as BLOBs and generate URLs
      response:
        docs: ''
        type: LocalUpdateResponse
      examples:
        - path-parameters:
            id: 1
          request: {}
          response:
            body:
              project: 1
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
      audiences:
        - public
    sync:
      path: /api/storages/localfiles/{id}/sync
      method: POST
      auth: true
      docs: Sync tasks from a local file import storage connection.
      path-parameters:
        id:
          type: integer
          docs: Storage ID
      display-name: Sync import storage
      response:
        docs: ''
        type: root.LocalFilesImportStorage
      examples:
        - path-parameters:
            id: 1
          response:
            body:
              id: 1
              type: type
              synchronizable: true
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              status: initialized
              traceback: traceback
              meta:
                meta:
                  key: value
              title: title
              description: description
              created_at: '2024-01-15T09:30:00Z'
              project: 1
      audiences:
        - public
types:
  LocalCreateResponse:
    properties:
      project:
        type: optional<integer>
        docs: Project ID
      path:
        type: optional<string>
        docs: Local path
      regex_filter:
        type: optional<string>
        docs: Regex for filtering objects
      use_blob_urls:
        type: optional<boolean>
        docs: Interpret objects as BLOBs and generate URLs
  LocalUpdateResponse:
    properties:
      project:
        type: optional<integer>
        docs: Project ID
      path:
        type: optional<string>
        docs: Local path
      regex_filter:
        type: optional<string>
        docs: Regex for filtering objects
      use_blob_urls:
        type: optional<boolean>
        docs: Interpret objects as BLOBs and generate URLs
