imports:
  root: ../__package__.yml
service:
  auth: false
  base-path: ''
  endpoints:
    list:
      path: /api/storages/export/localfiles
      method: GET
      auth: true
      docs: Get a list of all Local export storage connections.
      display-name: Get all export storage
      request:
        name: LocalListRequest
        query-parameters:
          project:
            type: optional<integer>
            docs: Project ID
      response:
        docs: ''
        type: list<root.LocalFilesExportStorage>
      examples:
        - response:
            body:
              - id: 1
                type: type
                synchronizable: true
                path: path
                regex_filter: regex_filter
                use_blob_urls: true
                last_sync: '2024-01-15T09:30:00Z'
                last_sync_count: 1
                last_sync_job: last_sync_job
                status: initialized
                traceback: traceback
                meta:
                  meta:
                    key: value
                title: title
                description: description
                created_at: '2024-01-15T09:30:00Z'
                can_delete_objects: true
                project: 1
    create:
      path: /api/storages/export/localfiles
      method: POST
      auth: true
      docs: Create a new local file export storage connection to store annotations.
      display-name: Create export storage
      request:
        name: LocalCreateRequest
        body:
          properties:
            project:
              type: optional<integer>
              docs: Project ID
            path:
              type: optional<string>
              docs: Local path
            regex_filter:
              type: optional<string>
              docs: Regex for filtering objects
            use_blob_urls:
              type: optional<boolean>
              docs: Interpret objects as BLOBs and generate URLs
      response:
        docs: ''
        type: LocalCreateResponse
      examples:
        - request: {}
          response:
            body:
              project: 1
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
    validate:
      path: /api/storages/export/localfiles/validate
      method: POST
      auth: true
      docs: Validate a specific local file export storage connection.
      display-name: Validate export storage
      response:
        docs: ''
        type: root.LocalFilesExportStorage
      examples:
        - response:
            body:
              id: 1
              type: type
              synchronizable: true
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              status: initialized
              traceback: traceback
              meta:
                meta:
                  key: value
              title: title
              description: description
              created_at: '2024-01-15T09:30:00Z'
              can_delete_objects: true
              project: 1
    get:
      path: /api/storages/export/localfiles/{id}
      method: GET
      auth: true
      docs: Get a specific local file export storage connection.
      path-parameters:
        id:
          type: integer
          docs: A unique integer value identifying this local files export storage.
      display-name: Get export storage
      response:
        docs: ''
        type: root.LocalFilesExportStorage
      examples:
        - path-parameters:
            id: 1
          response:
            body:
              id: 1
              type: type
              synchronizable: true
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              status: initialized
              traceback: traceback
              meta:
                meta:
                  key: value
              title: title
              description: description
              created_at: '2024-01-15T09:30:00Z'
              can_delete_objects: true
              project: 1
    delete:
      path: /api/storages/export/localfiles/{id}
      method: DELETE
      auth: true
      docs: Delete a specific local file export storage connection.
      path-parameters:
        id:
          type: integer
          docs: A unique integer value identifying this local files export storage.
      display-name: Delete export storage
      examples:
        - path-parameters:
            id: 1
    update:
      path: /api/storages/export/localfiles/{id}
      method: PATCH
      auth: true
      docs: Update a specific local file export storage connection.
      path-parameters:
        id:
          type: integer
          docs: A unique integer value identifying this local files export storage.
      display-name: Update export storage
      request:
        name: LocalUpdateRequest
        body:
          properties:
            project:
              type: optional<integer>
              docs: Project ID
            path:
              type: optional<string>
              docs: Local path
            regex_filter:
              type: optional<string>
              docs: Regex for filtering objects
            use_blob_urls:
              type: optional<boolean>
              docs: Interpret objects as BLOBs and generate URLs
      response:
        docs: ''
        type: LocalUpdateResponse
      examples:
        - path-parameters:
            id: 1
          request: {}
          response:
            body:
              project: 1
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
    sync:
      path: /api/storages/export/localfiles/{id}/sync
      method: POST
      auth: true
      docs: Sync tasks from a local file export storage connection.
      path-parameters:
        id: string
      display-name: Sync export storage
      response:
        docs: ''
        type: root.LocalFilesExportStorage
      examples:
        - path-parameters:
            id: id
          response:
            body:
              id: 1
              type: type
              synchronizable: true
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              status: initialized
              traceback: traceback
              meta:
                meta:
                  key: value
              title: title
              description: description
              created_at: '2024-01-15T09:30:00Z'
              can_delete_objects: true
              project: 1
types:
  LocalCreateResponse:
    properties:
      project:
        type: optional<integer>
        docs: Project ID
      path:
        type: optional<string>
        docs: Local path
      regex_filter:
        type: optional<string>
        docs: Regex for filtering objects
      use_blob_urls:
        type: optional<boolean>
        docs: Interpret objects as BLOBs and generate URLs
  LocalUpdateResponse:
    properties:
      project:
        type: optional<integer>
        docs: Project ID
      path:
        type: optional<string>
        docs: Local path
      regex_filter:
        type: optional<string>
        docs: Regex for filtering objects
      use_blob_urls:
        type: optional<boolean>
        docs: Interpret objects as BLOBs and generate URLs
